### ISSUE TITLE
Github интеграция в HwProj

### ISSUE THREAD

**Issue by AlexPoziev** [InteIIigeNET/HwProj-2.0.1#348]
## BigPicture
**Пользователь (Кто):** Преподаватели Программной Инженерии.
**Необходимость (Что):** Хочется, чтобы по сданной задаче было видно (или быть уверенным, что сданная задача) успешно прошли ли Github Actions и готова к проверке.

## DOD
- [ ] Появилась привязка Github-логина к студенту HwProj #349
- [ ] При открытии решения в HwProj сразу видно прошло ли решение Github Actions. Или задача сдается только при пройденном GA  #369 
- [ ] Создатель или преподаватель имеет возможность сгенерировать токен для курса #368
